image: golang:1.12

stages:
  - dependencies
  - setup
  - build

dependencies:
  stage: dependencies
  script: 
    - apt install protobuf-compiler
    - go mod download

setup:
  stage: setup
  script:
    - make api
  
build:
  stage: build
  script:
    - make build
