# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  GO111MODULE: 'on'
  GOBIN:  '$(GOPATH)/bin' # Go binaries path
  GOROOT: '/usr/local/go1.12' # Go installation path
  GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
  modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

steps:
- script: |
    mkdir -p '$(GOBIN)'
    mkdir -p '$(GOPATH)/pkg'
    mkdir -p '$(modulePath)'
    shopt -s extglob
    shopt -s dotglob
    mv !(gopath) '$(modulePath)'
    echo '##vso[task.prependpath]$(GOBIN)'
    echo '##vso[task.prependpath]$(GOROOT)/bin'
  displayName: 'Set up the Go workspace'

- script: |
    curl -OL https://github.com/protocolbuffers/protobuf/releases/download/v3.9.1/protoc-3.9.1-linux-x86_32.zip
    unzip protoc-3.9.1-linux-x86_32.zip -d protoc3
    sudo mv protoc3/bin/* /usr/local/bin/
    sudo mv protoc3/include/* /usr/local/include/
    echo '##vso[task.prependpath]/usr/local/bin'
    echo '##vso[task.prependpath]/usr/local/include'
  displayName: 'Set up protobuf'

- script: |
    go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-grpc-gateway
    go get -u github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger
    go get -u github.com/golang/protobuf/protoc-gen-go
    make api
  workingDirectory: '$(modulePath)'
  displayName: 'Generating protobuf'

- script: |
    go version
    echo "path"
    echo $PATH
    echo "bin"
    ls $GOROOT/bin
    ls $GOPATH/bin
    echo "gopath src"
    echo $GOPATH
    ls $GOPATH/src
    ls $GOPATH/src/github.com
    echo "gobinsrc"
    echo $GOBIN
    ls $GOBIN/src
    ls $GOBIN/src/github.com
    make build
  workingDirectory: '$(modulePath)'
  displayName: 'Get dependencies, then build'
