version: '3'
services:
  # Cockroachdb (https://www.cockroachlabs.com)
  cockroachdb:
    image: cockroachdb/cockroach:v2.1.3
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    # restart: "no"
    restart: always
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8085:8080"
volumes:
  data: